name: Pull Request - Check Protobuf

on:
  pull_request:
    paths:
      - 'proto/**/*.proto'

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
        - name : Checkout source
          uses: actions/checkout@v3
          with:
              ref: ${{ github.head_ref }}
        - name: Install Go
          uses: actions/setup-go@v3
          with:
              go-version: 1.20
              check-latest: true
        - name: Generate Go Source
          shell: bash
          run: |
              make build
