name: Pull Request - Check Protobuf

on:
  pull_request:
    paths:
      - 'proto/**/*.proto'

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
        - name : Checkout source
          uses: actions/checkout@v3
          with:
              ref: ${{ github.head_ref }}

        - name: Install Go
          uses: actions/setup-go@v3
          with:
              go-version: 1.20
              check-latest: true

        - name: Set up Go environment
          run: |
            export GOPATH=$HOME/go
            export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
            export GOROOT=/usr/local/go
            export GO111MODULE=on

        - name: Install protoc
          run: |
            sudo apt-get install -y protobuf-compiler golang-goprotobuf-dev
            go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
            go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

        - name: Generate Go Source
          shell: bash
          run: |
              make build
